### ISSUE TITLE
DialogBox Footer UI is not working as expected

### ISSUE THREAD

**Issue by tenzincopart** [copartit/g2-ops-component-library#116]
**Describe the bug**
DialogBox Footer UI is not working as expected

**Steps To Reproduce**
(You don't have to include cloning, installing, and starting the app.)
1. Run UK Engineering project locally
2. Currently UK Engineering has a clone of g2 core DialogBox. Modify the code to import the DialogBox from g2 core
3. Open Assign Engineering Dialog
4. The Footer UI is messed up. 

**Expected behavior**
Smooth UI with grey footer without any extra margin around the footer.

**Additional context**
From the g2 core itself, the dialog footer is working just fine. The issue is that, when you use the DialogBox by importing into a project outside, it does not work.

**Comment by colshacol** [comment]
I can't get uk-engineering running on my machine. ¯\_(ツ)_/¯ Guess I'm out.

**Comment by tenzincopart** [comment]
@revanthCopart - can you please help @colshacol

**Comment by colshacol** [comment]
This issue is resolved. The issue was not with core-components.
