### ISSUE TITLE
Input Fields layout options (TextField, PhoneNumber, AutoSelect, etc)

### ISSUE THREAD

**Issue by tenzincopart** [copartit/g2-ops-component-library#117]
**Is your feature request related to a problem? Please describe.**
Input fields are being used across different applications with different layout requirement and having an option to have the label position on top of the input field as well as to the left of the input field is crucial. 

Need to have an prop to choose the layout of all the input fields with regard to its label. Currently, the label is aligned on top of the text field. 

**Describe the solution you'd like**
`null`

**Describe alternatives you've considered**
Pass a props/flag that handles the label position in relative to the input field

**Additional context**
Can we also make the label color #1d5ab9 or have an option to pass a color for the label. 
Seems like AutoSelect currently does not have label. Can we have label there as well?

**Comment by colshacol** [comment]
The label color will be whatever the UX spec dictates. We can not provide such flexibility as to provide custom coloring.

![screen shot 2018-08-28 at 12 49 10 pm](https://user-images.githubusercontent.com/19484365/44740717-ca57e200-aac0-11e8-9d5e-a4f6ec0d7948.png)

This is what happens when we can choose our own colors. 🤣

**Comment by colshacol** [comment]
The prop will be `labelPosition`, it will accept a string enum that can either be `"left"` or `"top"` and default to top.

**Comment by tenzincopart** [comment]
@colshacol - Then I think the label color has to be #1d5ab9. Do you agree?

**Comment by colshacol** [comment]
From reading #118 and looking at the example images provided, it seems to cover all three TextField components.

**Comment by colshacol** [comment]
That's what I gathered from it, at least.

<img width="647" alt="screen shot 2018-08-29 at 11 35 42 am" src="https://user-images.githubusercontent.com/19484365/44801819-b0c99f80-ab7f-11e8-8df4-8c93a288b6fb.png">

@ClintonBaker Is this correct that your fix _works for all 3 variations of the TextField_?

**Comment by tenzincopart** [comment]
@colshacol - yeah... from the screenshot above, looks like PhoneNumber was done but not AutoSelect. But as I looked at the files changed, I only see changes in the TextField and not for PhoneNumber.js. So I just assumed that the changes were not added there. Can you please confirm @ClintonBaker ? Thanks!

**Comment by colshacol** [comment]
PhoneNumber and AutoSelect both are proxies for TextField. So, from testing this locally, I see that the change to TextField affected PhoneNumber and AutoSelect. :+1:

The image is hard to interpret, I agree, but I do see PhoneNumber and AutoSelect there with labels on the left. ;)

**Comment by tenzincopart** [comment]
Thanks @colshacol

**Comment by colshacol** [comment]
@christiandardenne We could do something similar to what we did with the phone number input and give an indicator if there is an error and provide more information via tool-tip or something when the user hovers. This would allow us to preserve real estate and when they hovered, the tip would be absolute positioned, so it wouldn't need to move any other elements around, it'd just chill on top of them.

![screen shot 2018-08-29 at 7 11 08 pm](https://user-images.githubusercontent.com/19484365/44822197-5f410500-abbf-11e8-9ef4-e50131410bd2.png)
![screen shot 2018-08-29 at 7 11 22 pm](https://user-images.githubusercontent.com/19484365/44822198-5f410500-abbf-11e8-8dbf-f61ce03d2764.png)
